import Head from 'next/head'
import Navbar from './Navbar'
import styles from '../styles/Layout.module.css'
import { Inter, Ubuntu_Mono } from '@next/font/google'

const ubuntuMono = Ubuntu_Mono({ subsets: ['latin'], weight: ['400', '700'] })
const inter = Inter({ subsets: ['latin'] })

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={ubuntuMono.className}>
        <Navbar />
        <main className={styles.container}>
          {children}
        </main>
      </div>
    </>
  )
}

export default Layout